"""
Export N-gram Model to TypeScript
Reads models/ngram_model.json and generates src/lib/ngramModel.ts

Usage:
    python export_ngram_ts.py
"""

import json
import os
import sys


def main():
    input_path = os.path.join("models", "ngram_model.json")
    output_path = os.path.join("phishguard-v2", "src", "lib", "ngramModel.ts")

    if not os.path.exists(input_path):
        print(f"Error: {input_path} not found.")
        print("Run training.py first to generate the n-gram model.")
        sys.exit(1)

    with open(input_path, "r") as f:
        data = json.load(f)

    ngrams = data.get("ngrams", {})
    total = data.get("total", 0)
    vocab_size = data.get("vocab_size", 38)

    # Filter to trigrams with probability > 0.0001
    filtered = {k: v for k, v in ngrams.items() if v > 0.0001}

    lines = [
        '// Auto-generated by export_ngram_ts.py — do not edit manually',
        f'// Generated from {len(filtered)} trigrams (filtered from {len(ngrams)} total)',
        '',
        'export const NGRAM_MODEL: Record<string, number> = {',
    ]

    for key, value in sorted(filtered.items()):
        escaped_key = key.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'  "{escaped_key}": {value:.6f},')

    lines.append('};')
    lines.append('')
    lines.append(f'export const NGRAM_TOTAL = {total};')
    lines.append('')
    lines.append(f'export const NGRAM_VOCAB_SIZE = {vocab_size};')
    lines.append('')

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w") as f:
        f.write("\n".join(lines))

    print(f"✅ TypeScript n-gram model written to {output_path}")
    print(f"   {len(filtered)} trigrams exported")


if __name__ == "__main__":
    main()
