name: Train Phishing Detection Models

on:
  push:
    paths:
      - 'training.py'
      - '.github/workflows/train.yml'
      - 'requirements.txt'

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run training script
      run: |
        python training.py

    - name: Upload trained models
      uses: actions/upload-artifact@v4
      with:
        name: phishing-detector-models
        path: models/
